import Foundation

/// 快速跳转到预定义路径的条目
struct QuickJumpEntry: Identifiable, Hashable {
    let id: String          // 展示名称（枚举键名）
    let path: String        // 完整 S3 对象前缀路径（含文件名前缀）
    let altPath: String     // 备用路径（部分条目有第二条路径）

    /// 提取目录前缀（strip 最后一个 / 之后的文件名前缀部分）
    var directoryPrefix: String {
        if path.hasSuffix("/") { return path }
        guard let slashIndex = path.lastIndex(of: "/") else { return "" }
        return String(path[path.startIndex...slashIndex])
    }

    static let all: [QuickJumpEntry] = [
        QuickJumpEntry(id: "ACKNOWLEDGEMENT",                              path: "vodapay/filesFromBidvest/Acknowledgement_",                                                              altPath: ""),
        QuickJumpEntry(id: "EOD_TRANSACTION_REQ",                          path: "FromAntFinancial/SOV/AggregateEOD/done/EODTransactionAggregation",                                      altPath: ""),
        QuickJumpEntry(id: "EOD_TRANSACTION_RES",                          path: "ToAntFinancial/SOV/AggregateEOD/Accepted/done/AcceptedEODTransactionAggregation",                       altPath: ""),
        QuickJumpEntry(id: "SOV_PENDING",                                  path: "FromAntFinancial/SOV/Pending/done/sov_pending_transactions_",                                            altPath: ""),
        QuickJumpEntry(id: "SOV_AML_KYC",                                  path: "vodapay/filesToBidvest/kyc/done/Transactions_customer_sov_",                                            altPath: ""),
        QuickJumpEntry(id: "SOV_AML_INDIVIDUAL",                           path: "vodapay/filesToBidvest/kyc/done/Customer_details_individuals_",                                         altPath: ""),
        QuickJumpEntry(id: "SOV_AML_CONTROL_FILE",                         path: "vodapay/filesToBidvest/kyc/done/ControlFile_",                                                          altPath: ""),
        QuickJumpEntry(id: "SOV_AML_ACCOUNT_BALANCE_CUSTOMER",             path: "vodapay/filesToBidvest/kyc/done/Account_balance_customer_sov_",                                         altPath: ""),
        QuickJumpEntry(id: "SOV_AML_ACCOUNT_CUSTOMER",                     path: "vodapay/filesToBidvest/kyc/done/Account_customer_sov_",                                                 altPath: ""),
        QuickJumpEntry(id: "SOV_AML_NETT_MOVEMENT",                        path: "vodapay/filesToBidvest/kyc/done/nett_movement_report_",                                                 altPath: ""),
        QuickJumpEntry(id: "VIRTUALCARD_DUMP_FILE",                        path: "ToAntFinancial/virtualcard/dump/done/VODAPAY_TRANSACTION_DUMP_334_",                                              altPath: ""),
        QuickJumpEntry(id: "VAS_RECON",                                    path: "FromAntFinancial/VAS/Alipayplus_vas_recon_",                                                            altPath: ""),
        QuickJumpEntry(id: "EFT_IN_RETRY",                                 path: "ToAntFinancial/SOV/Retry/done/alipayplus_eft_retail_deposit_retry_request_",                            altPath: ""),
        QuickJumpEntry(id: "EFT_IN_ROLLBACK",                              path: "Financial/SOV/Error/EFT_In_Rollback_",                                                                  altPath: ""),
        QuickJumpEntry(id: "EFT_IN_UNPAID_REQ",                            path: "FromAntFinancial/SOV/Unpaid/done/ItemizedUnpaids",                                                      altPath: ""),
        QuickJumpEntry(id: "EFT_IN_UNPAID_RES",                            path: "ToAntFinancial/SOV/Unpaid/Accepted/done/AcceptedItemizedUnpaids",                                       altPath: ""),
        QuickJumpEntry(id: "EFT_IN_RECON_REQ",                             path: "FromAntFinancial/SOV/Markoff/done/alipayplus_eft_retail_deposit_recon_request_",                        altPath: ""),
        QuickJumpEntry(id: "EFT_IN_RECON_RES",                             path: "ToAntFinancial/SOV/Markoff/done/alipayplus_eft_retail_deposit_recon_response_",                         altPath: ""),
        QuickJumpEntry(id: "EFT_RETAIL_DEPOSIT_SETTLEMENT_SERIALS",        path: "FromAntFinancial/SOV/SettlementSerials/done/alipayplus_eft_retail_deposit_settlement_serials_request_",  altPath: ""),
        QuickJumpEntry(id: "EFT_RETAIL_SETTLEMENT_SETTLEMENT_SERIALS",     path: "FromAntFinancial/SOV/SettlementSerials/done/alipayplus_eft_retail_settlement_settlement_serials_request_", altPath: ""),
        QuickJumpEntry(id: "CASHOUT_FILE",                                 path: "FromAntFinancial/SOV/Cashout/Outgoing/EFT/done/VDCSCI01",                                               altPath: ""),
        QuickJumpEntry(id: "CASHOUT_FILE_Backup",                          path: "FromAntFinancial/SOV/Cashout/Outgoing/EFT/Archive/VDCSCI01_",                                           altPath: ""),
        QuickJumpEntry(id: "CASHOUT_REJECT",                               path: "ToAntFinancial/SOV/Cashout/Incoming/Vet-Unpaid/done/VDCVTF01_",                                         altPath: ""),
        QuickJumpEntry(id: "CASHOUT_UNPAID",                               path: "ToAntFinancial/SOV/Cashout/Incoming/Vet-Unpaid/done/VDCUCO01_",                                         altPath: ""),
        QuickJumpEntry(id: "CASHOUT_RECON_REQ",                            path: "FromAntFinancial/SOV/Markoff/done/alipayplus_eft_retail_withdraw_recon_request_",                        altPath: ""),
        QuickJumpEntry(id: "CASHOUT_RECON_RES",                            path: "ToAntFinancial/SOV/Markoff/done/alipayplus_eft_retail_withdraw_recon_response_",                         altPath: ""),
        QuickJumpEntry(id: "CASHOUT_UNPAID_RECON_REQ",                     path: "FromAntFinancial/SOV/Markoff/done/alipayplus_retail_withdraw_unpaid_recon_request_",                     altPath: ""),
        QuickJumpEntry(id: "CASHOUT_UNPAID_RECON_RES",                     path: "ToAntFinancial/SOV/Markoff/done/alipayplus_retail_withdraw_unpaid_recon_response_",                      altPath: ""),
        QuickJumpEntry(id: "CASHOUT_SETTLEMENT_SERIALS",                   path: "FromAntFinancial/SOV/SettlementSerials/done/alipayplus_eft_retail_withdraw_settlement_serials_request_",  altPath: ""),
        QuickJumpEntry(id: "BB_FLOAT_GAP",                                 path: "FromAntFinancial/SOV/Pending/done/Float_gap_report_",                                                   altPath: ""),
        QuickJumpEntry(id: "SEC_FILE",                                     path: "ToAntFinancial/SOV/Sec/done/BSYDB001_",                                                                 altPath: ""),
        QuickJumpEntry(id: "SEC_RECON_REQ",                                path: "FromAntFinancial/SOV/Markoff/done/alipayplus_sec_retail_deposit_recon_request_",                         altPath: ""),
        QuickJumpEntry(id: "SEC_REJECT_REQ",                               path: "FromAntFinancial/SOV/Unsuccessful/alipayplus_sec_retail_deposit_unsuccessful_request_",                  altPath: ""),
        QuickJumpEntry(id: "SEC_SETTLEMENT_SERIALS",                       path: "FromAntFinancial/SOV/SettlementSerials/done/alipayplus_sec_retail_deposit_settlement_serials_",           altPath: ""),
        QuickJumpEntry(id: "SOV_PAYMENT_RECON_REQ",                        path: "FromAntFinancial/SOV/Markoff/done/alipayplus_sov_payment_recon_",                                        altPath: ""),
        QuickJumpEntry(id: "SOV_PAYMENT_RECON_RES",                        path: "ToAntFinancial/SOV/Markoff/done/alipayplus_sov_payment_recon_response_",                                 altPath: ""),
        QuickJumpEntry(id: "SOV_PAYMENT_SETTLEMENT_SERIALS",               path: "FromAntFinancial/SOV/SettlementSerials/done/alipayplus_sov_payment_settlement_serials_request_",          altPath: ""),
        QuickJumpEntry(id: "SOV_REFUND_RECON_REQ",                         path: "FromAntFinancial/SOV/Markoff/done/alipayplus_refund_recon_",                                             altPath: ""),
        QuickJumpEntry(id: "SOV_REFUND_RECON_RES",                         path: "ToAntFinancial/SOV/Markoff/done/alipayplus_refund_recon_response_",                                      altPath: ""),
        QuickJumpEntry(id: "REFUND_COUPON_REPORT",                         path: "FromAntFinancial/SOV/coupon/report/alipayplus_refund_coupon_report_",                                    altPath: ""),
        QuickJumpEntry(id: "DEPOSIT_AT_RETAIL_RECON_REQ",                  path: "FromAntFinancial/SOV/Markoff/done/alipayplus_retail_deposit_at_retailer_recon_request_",                  altPath: ""),
        QuickJumpEntry(id: "DEPOSIT_AT_RETAIL_RECON_RES",                  path: "ToAntFinancial/SOV/Markoff/done/alipayplus_retail_deposit_at_retailer_recon_response_",                   altPath: ""),
        QuickJumpEntry(id: "DEPOSIT_AT_RETAIL_RETRY_FILE",                 path: "ToAntFinancial/SOV/Retry/done/alipayplus_retail_deposit_at_retailer_retry_request_",                      altPath: ""),
        QuickJumpEntry(id: "NANO_LOANS_RECON_REQ",                         path: "FromAntFinancial/SOV/Markoff/done/alipayplus_loan_retail_deposit_recon_request_",                         altPath: ""),
        QuickJumpEntry(id: "NANO_LOANS_RECON_RES",                         path: "ToAntFinancial/SOV/Markoff/done/alipayplus_loan_retail_deposit_recon_response_",                          altPath: ""),
        QuickJumpEntry(id: "BANKCARD_DEPOSIT_REQ",                         path: "FromAntFinancial/SOV/Markoff/done/alipayplus_retail_card_deposit_recon_request_",                         altPath: ""),
        QuickJumpEntry(id: "BANKCARD_DEPOSIT_RES",                         path: "ToAntFinancial/SOV/Markoff/done/alipayplus_retail_card_deposit_recon_response_",                          altPath: ""),
        QuickJumpEntry(id: "BANKCARD_DEPOSIT_SETTLEMENT_SERIALS",          path: "FromAntFinancial/SOV/SettlementSerials/done/alipayplus_retail_card_deposit_settlement_serials_request_",   altPath: ""),
        QuickJumpEntry(id: "LOTTO_RETAIL_DEPOSIT_RECON_REQ",               path: "FromAntFinancial/SOV/Markoff/done/alipayplus_lotto_retail_deposit_recon_request_",                        altPath: ""),
        QuickJumpEntry(id: "LOTTO_RETAIL_DEPOSIT_RECON_RES",               path: "ToAntFinancial/SOV/Markoff/done/alipayplus_lotto_retail_deposit_recon_response_",                         altPath: ""),
        QuickJumpEntry(id: "LOTTO_RETAIL_DEPOSIT_SETTLEMENT_SERIALS",      path: "FromAntFinancial/SOV/SettlementSerials/done/alipayplus_lotto_retail_deposit_settlement_serials_request_",  altPath: ""),
        QuickJumpEntry(id: "RETAIL_CASH_WITHDRAW_RECON_REQ",               path: "FromAntFinancial/SOV/Markoff/done/alipayplus_retail_cash_withdraw_recon_request_",                        altPath: ""),
        QuickJumpEntry(id: "RETAIL_CASH_WITHDRAW_RECON_RES",               path: "ToAntFinancial/SOV/Markoff/done/alipayplus_retail_cash_withdraw_recon_response_",                         altPath: ""),
        QuickJumpEntry(id: "RETAIL_CASH_WITHDRAW_SETTLEMENT_SERIALS",      path: "FromAntFinancial/SOV/SettlementSerials/done/alipayplus_retail_cash_withdraw_settlement_serials_request_",  altPath: ""),
        QuickJumpEntry(id: "RETAIL_CASH_WITHDRAW_FEE_SETTLEMENT_SERIALS",  path: "FromAntFinancial/SOV/SettlementSerials/done/alipayplus_retail_cash_withdraw_fee_settlement_serials_request_", altPath: ""),
        QuickJumpEntry(id: "RETAIL_DOMESTIC_REMITTANCE_SERIALS",           path: "FromAntFinancial/SOV/SettlementSerials/done/alipayplus_retail_domestic_remittance_settlement_serials_request_", altPath: ""),
        QuickJumpEntry(id: "RETAIL_DOMESTIC_REMITTANCE_FEE_SERIALS",       path: "FromAntFinancial/SOV/SettlementSerials/done/alipayplus_retail_domestic_remittance_fee_settlement_serials_request_", altPath: ""),
        QuickJumpEntry(id: "BIDVEST_INBOUND_MARKOFF_FILE",                 path: "ToAntFinancial/SOV/Markoff/done/EFTInboundMarkoff",                                                      altPath: ""),
        QuickJumpEntry(id: "FUND_BUSINESS_MARKOFF_FILE",                   path: "FromAntFinancial/SOV/Fund/done/alipayplus_eft_retail_deposit_recon_request_",                             altPath: ""),
        QuickJumpEntry(id: "EOD_REJECTED_FILE",                            path: "ToAntFinancial/SOV/AggregateEOD/Rejected/done/",                                                         altPath: ""),
        QuickJumpEntry(id: "UNPAID_REJECTED_FILE",                         path: "ToAntFinancial/SOV/Unpaid/Rejected/done/",                                                               altPath: ""),
        QuickJumpEntry(id: "PROMOTION_CASH_BACK_SETTLEMENT_SERIALS",       path: "FromAntFinancial/SOV/SettlementSerials/done/alipayplus_cashback_retail_deposit_settlement_serials_request_", altPath: ""),
        QuickJumpEntry(id: "VODABUCKS_TO_SOV_RECON_REQ",                   path: "FromAntFinancial/SOV/Markoff/done/alipayplus_vodabucks_cashback_retail_deposit_recon_request_",            altPath: ""),
        QuickJumpEntry(id: "VODABUCKS_CASH_BACK_SETTLEMENT_SERIALS",       path: "FromAntFinancial/SOV/SettlementSerials/done/alipayplus_vodabucks_cashback_retail_deposit_settlement_serials_request_", altPath: ""),
        QuickJumpEntry(id: "CASHBACK_AS_REWARD_RECON_REQ",                 path: "FromAntFinancial/SOV/Markoff/done/alipayplus_sovrewards_cashback_retail_deposit_recon_request_",           altPath: ""),
        QuickJumpEntry(id: "KFC_Data",                                     path: "ToAntFinancial/payments/kfc/done/TotalOrderReport_",                                                     altPath: "ToAntFinancial/KFC/Rewards/done/TotalOrderReport_"),
        QuickJumpEntry(id: "PROMOTION_REWARD_File",                        path: "ToAntFinancial/Promotion/reward/alipayplus_promotion_reward_",                                           altPath: ""),
        QuickJumpEntry(id: "BULK_DISBURSE_BDEFTInboundMarkoff",            path: "ToAntFinancial/SOV/BulkDisbursement/InBoundMarkOff/done/BDEFTInboundMarkoff",                             altPath: ""),
        QuickJumpEntry(id: "BULK_DISBURSE_AcceptedBDEFTInboundMarkoff",    path: "FromAntFinancial/BulkDisbursement/Accepted/done/AcceptedBDEFTInboundMarkoff",                             altPath: ""),
        QuickJumpEntry(id: "BULK_UNPAID_REQ",                              path: "FromAntFinancial/BulkDisbursement/UnPaid/done/BDItemizedUnpaids",                                        altPath: ""),
        QuickJumpEntry(id: "BULK_Statements",                              path: "FromAntFinancial/BulkDisbursements/Statements/pdf/",                                                     altPath: ""),
        QuickJumpEntry(id: "BULK_DISBURSE_SOV_PAYMENT_RECON_REQ",          path: "FromAntFinancial/SOV/Markoff/done/alipayplus_bulk_disburse_sov_payment_recon_request_",                   altPath: ""),
        QuickJumpEntry(id: "BULK_DISBURSE_SOV_PAYMENT_SETTLEMENT",         path: "FromAntFinancial/SOV/SettlementSerials/done/alipayplus_bulk_disburse_sov_payment_settlement_serials_request_", altPath: ""),
        QuickJumpEntry(id: "BULK_DISBURSE_DEPOSIT_RECON_REQ",              path: "FromAntFinancial/SOV/Markoff/done/alipayplus_bulk_disburse_deposit_recon_request_",                       altPath: ""),
        QuickJumpEntry(id: "BULK_DISBURSE_DEPOSIT_SETTLEMENT",             path: "FromAntFinancial/SOV/SettlementSerials/done/alipayplus_bulk_disburse_deposit_settlement_serials_request_", altPath: ""),
        QuickJumpEntry(id: "BULK_DISBURSE_SERVICE_FEE_SETTLEMENT",         path: "FromAntFinancial/SOV/SettlementSerials/done/alipayplus_bulk_disburse_service_fee_settlement_serials_request_", altPath: ""),
        QuickJumpEntry(id: "BULK_INITIATION_FEE_SETTLEMENT",               path: "FromAntFinancial/SOV/SettlementSerials/done/alipayplus_bulk_disburse_initiation_fee_settlement_serials_request_", altPath: ""),
        QuickJumpEntry(id: "EASY_PAY_VOAP_BPS",                            path: "ToAntFinancial/DailyReports/VOAP.BPS.markup.",                                                          altPath: ""),
        QuickJumpEntry(id: "EASY_PAY_VOAP_CEL",                            path: "ToAntFinancial/DailyReports/VOAP.CEL.markup.",                                                          altPath: ""),
        QuickJumpEntry(id: "EASY_PAY_VOAP_PRE",                            path: "ToAntFinancial/DailyReports/VOAP.PRE.markup.",                                                          altPath: ""),
        QuickJumpEntry(id: "PRD179_Stitch_RECON_REQ",                      path: "ToAntFinancial/SOV/Stitch/test4/done/VodaPayUAT_",                                                      altPath: ""),
        QuickJumpEntry(id: "PRD179_APLUS_RECON_RES",                       path: "FromAntFinancial/SOV/Markoff/done/alipayplus_retail_instant_deposit_recon_response_",                     altPath: ""),
        QuickJumpEntry(id: "PROD_LOGS_ARCHIVE",                            path: "aplus-prod-logs-error/logs/ifcsupergw/error",                                                           altPath: ""),
    ]
}
